/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotovoltaikRouteImport } from './routes/photovoltaik'
import { Route as StromspeicherRouteImport } from './routes/stromspeicher'
import { Route as WaermepumpeRouteImport } from './routes/waermepumpe'
import { Route as WallboxRouteImport } from './routes/wallbox'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotovoltaikRoute = PhotovoltaikRouteImport.update({
  id: '/photovoltaik',
  path: '/photovoltaik',
  getParentRoute: () => rootRouteImport,
} as any)
const StromspeicherRoute = StromspeicherRouteImport.update({
  id: '/stromspeicher',
  path: '/stromspeicher',
  getParentRoute: () => rootRouteImport,
} as any)
const WaermepumpeRoute = WaermepumpeRouteImport.update({
  id: '/waermepumpe',
  path: '/waermepumpe',
  getParentRoute: () => rootRouteImport,
} as any)
const WallboxRoute = WallboxRouteImport.update({
  id: '/wallbox',
  path: '/wallbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/photovoltaik': typeof PhotovoltaikRoute
  '/stromspeicher': typeof StromspeicherRoute
  '/waermepumpe': typeof WaermepumpeRoute
  '/wallbox': typeof WallboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/photovoltaik': typeof PhotovoltaikRoute
  '/stromspeicher': typeof StromspeicherRoute
  '/waermepumpe': typeof WaermepumpeRoute
  '/wallbox': typeof WallboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/photovoltaik': typeof PhotovoltaikRoute
  '/stromspeicher': typeof StromspeicherRoute
  '/waermepumpe': typeof WaermepumpeRoute
  '/wallbox': typeof WallboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/photovoltaik' | '/stromspeicher' | '/waermepumpe' | '/wallbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/photovoltaik' | '/stromspeicher' | '/waermepumpe' | '/wallbox'
  id:
    | '__root__'
    | '/'
    | '/photovoltaik'
    | '/stromspeicher'
    | '/waermepumpe'
    | '/wallbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhotovoltaikRoute: typeof PhotovoltaikRoute
  StromspeicherRoute: typeof StromspeicherRoute
  WaermepumpeRoute: typeof WaermepumpeRoute
  WallboxRoute: typeof WallboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photovoltaik': {
      id: '/photovoltaik'
      path: '/photovoltaik'
      fullPath: '/photovoltaik'
      preLoaderRoute: typeof PhotovoltaikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stromspeicher': {
      id: '/stromspeicher'
      path: '/stromspeicher'
      fullPath: '/stromspeicher'
      preLoaderRoute: typeof StromspeicherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waermepumpe': {
      id: '/waermepumpe'
      path: '/waermepumpe'
      fullPath: '/waermepumpe'
      preLoaderRoute: typeof WaermepumpeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallbox': {
      id: '/wallbox'
      path: '/wallbox'
      fullPath: '/wallbox'
      preLoaderRoute: typeof WallboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhotovoltaikRoute: PhotovoltaikRoute,
  StromspeicherRoute: StromspeicherRoute,
  WaermepumpeRoute: WaermepumpeRoute,
  WallboxRoute: WallboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
